# 异常体系
- `RuntimeException` 
- `非RuntimeException` 编译时异常，在写的时候已经有红线提示了

![](https://obsidian-1307744200.cos.ap-guangzhou.myqcloud.com/%E5%9B%BE%E7%89%87/202403031014287.png)

>[!hint] JVM 会自己默认处理异常，那我们为什么还要自己处理呢？
>因为 JVM 的默认处理方案会终止程序的运行，但我们在实际开发中就算程序出错了，我们依然还要继续运行

# 异常处理
## try…catch…
```java
try {
	可能出现异常的代码
	……
} catch(异常类名，变量名) {
	异常处理的代码
	……
}
```

执行流程：
1. 执行 try 内的代码
	1. 


## throws



# 实例
## 注释异常
```java
System.out.println("bug");   //\u000A is a newline

---
java: 需要';'
```
>由于注释里的<mark style="background: #D2B3FFA6;">\u000A</mark>导致的，因为读程序时\u000A会转换为一个换行符

---

```java
System.out.println("bug");   //look inside c:\users

---
非法的Unicode转义
```
>由于\u后面没有跟着4位的十六进制数






























































